name = "solengine-website"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "solengine-forum"
database_id = "0df42170-ac0f-43cc-98b4-2c974e3eb100"

[[kv_namespaces]]
binding = "SESSION_STORE"
id = "a8d8dcef775348cd97efeff9d61ece38"
